# Streamlit UI Theme
# Docs:
# - https://docs.streamlit.io/develop/concepts/configuration/theming

[theme]
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1B2230"
textColor = "#FAFAFA"
font = "sans serif"
baseFontSize = 16
baseFontWeight = 450

[theme.sidebar]
secondaryBackgroundColor = "#0B0F14"
baseFontSize = 15
baseFontWeight = 450
